# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.synced_folder  ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provision "shell", inline: <<-SHELL
    if mount | grep /mnt > /dev/null; then
      umount /mnt
    fi
  SHELL
  
end
